config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins

  resources :admin, only: %i[index]

  namespace :admin do
    resources :products do
      resources :stocks
    end
    resources :categories
    resources :orders
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ('/')
  root to: 'home#index'

  authenticated :admin_user do
    root to: 'admin#index', as: :admin_root
  end

  resources :categories, only: %i[index show]
  resources :products, only: %i[index show]

  post 'checkout' => 'checkouts#create'
  get 'cart' => 'carts#show'

  # Route to handle external reference in chart.js
  get '/_/:filename', to: 'assets#serve_js', constraints: { filename: /.*\.js/ }

  # Stripe routes
  get 'stripe_payment_success' => 'checkouts#success'
  get 'stripe_payment_cancel' => 'checkouts#cancel'
  post 'stripe_webhooks' => 'webhooks#stripe'
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :order_products
  has_many :products, through: :order_products
end

app/controllers/admin/orders_controller.rb
# frozen_string_literal: true

class Admin::OrdersController < AdminController
  before_action :set_order, only: %i[show edit update destroy]

  # GET /orders or /orders.json
  def index
    @pagy_unfulfilled, @orders_unfulfilled = pagy(Order.where(fulfilled: false).order(created_at: :desc))
    @pagy_fulfilled, @orders_fulfilled = pagy(Order.where(fulfilled: true).order(created_at: :desc),
                                              page_param: :page_fulfilled)
  end

  # GET /orders/1 or /orders/1.json
  def show; end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit; end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to admin_order_url(@order), notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to admin_order_url(@order), notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy!

    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.require(:order).permit(:customer_email, :fulfilled, :total, :address)
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_with(model: [:admin, order], class: "contents") do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :customer_email %>
    <%= form.text_field :customer_email, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :fulfilled %>
    <%= form.check_box :fulfilled, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :total %>
    <%= form.number_field :total, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_field :address, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Customer email:</strong>
    <%= order.customer_email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Fulfilled:</strong>
    <%= order.fulfilled %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Total:</strong>
    <%= order.total %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= order.address %>
  </p>

</div>

app/views/admin/orders/_orders.html.erb
<div id="admin_orders" class="flex flex-col w-full">
  <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5">
    <div class="py-2 inline-block min-w-full">
      <div class="overflow-x-auto">
        <table class="min-w-full overflow-x-scroll">
          <thead class="bg-white border-b">
            <tr>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                ID
              </th>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                Customer email
              </th>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                Total
              </th>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                Address
              </th>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                Fulfilled
              </th> 
            </tr>
          </thead>
          <tbody>
            <% orders.each do |order| %>
              <tr class="bg-gray-50 border-b">
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 underline">
                  <strong>
                    <%= link_to order.id, admin_order_path(order) %>
                  </strong>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                  <%= order.customer_email.presence || 'unknown' %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                  <%= order.total.presence || '-' %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                  <%= order.address.presence || 'unknown' %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                  <%= order.fulfilled %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <%== pagy_nav(pagy) if pagy.pages > 1 %>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing order</h1>

  <%= render "form", order: @order %>

  <%= link_to "Show this order",
              admin_order_path(@order),
              class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to orders",
              admin_orders_path,
              class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/orders/index.html.erb
<div class="w-full">
  <% content_for :title, "Orders" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Orders</h1>
    <%= link_to "New order", new_admin_order_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <h2>Unfulfilled Orders</h2>
  <%= render 'orders', orders: @orders_unfulfilled, pagy: @pagy_unfulfilled %>
  
  <h2>Fulfilled Orders</h2>
  <%= render 'orders', orders: @orders_fulfilled, pagy: @pagy_fulfilled %>
</div>

app/views/admin/orders/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New order</h1>

  <%= render "form", order: @order %>

  <%= link_to "Back to orders", 
              admin_orders_path, 
              class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/orders/show.html.erb
<div class="md:w-2/3 w-full flex">
  <div>
    <%= render @order %>

    <%= link_to "Edit this order",
                edit_admin_order_path(@order), 
                class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to orders", 
                admin_orders_path, 
                class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this order", 
                    admin_order_path(@order), 
                    method: :delete, 
                    class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>