config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins

  resources :admin, only: %i[index]

  namespace :admin do
    resources :products do
      resources :stocks
    end
    resources :categories
    resources :orders
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ('/')
  root to: 'home#index'

  authenticated :admin_user do
    root to: 'admin#index', as: :admin_root
  end

  resources :categories, only: %i[index show]
  resources :products, only: %i[index show]

  post 'checkout' => 'checkouts#create'
  get 'cart' => 'carts#show'

  # Route to handle external reference in chart.js
  get '/_/:filename', to: 'assets#serve_js', constraints: { filename: /.*\.js/ }

  # Stripe routes
  get 'stripe_payment_success' => 'checkouts#success'
  get 'stripe_payment_cancel' => 'checkouts#cancel'
  post 'stripe_webhooks' => 'webhooks#stripe'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

# a class to create categories
class Category < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
    attachable.variant :medium, resize_to_limit: [250, 250]
  end

  has_many :products
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :order_products
  has_many :products, through: :order_products
end

app/models/order_product.rb
# frozen_string_literal: true

class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
# frozen_string_literal: true

# a class to create products
class Product < ApplicationRecord
  belongs_to :category

  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
    attachable.variant :medium, resize_to_limit: [250, 250]
  end
  has_many :stocks
  has_many :order_products
  has_many :orders, through: :order_products
end

app/models/stock.rb
# frozen_string_literal: true

class Stock < ApplicationRecord
  belongs_to :product
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  before_action :authenticate_admin!

  layout 'admin'

  def index
    today_start = Time.zone.now.midnight - 7.days
    today_end = Time.zone.now.midnight.end_of_day

    query = <<-SQL
      SELECT
        COUNT(DISTINCT orders.id) AS orders_count,
        COUNT(DISTINCT order_products.id) AS order_products_count,
        SUM(total) AS total_sum,
        AVG(total) AS total_average
      FROM orders
      LEFT JOIN order_products ON orders.id = order_products.order_id
      WHERE orders.created_at >= '#{today_start}' AND orders.created_at <= '#{today_end}';
    SQL

    todays_orders = ActiveRecord::Base.connection.execute(query).first

    @dashboard_data = {
      revenue: todays_orders['total_sum'],
      orders_count: todays_orders['orders_count'],
      avg_sale: todays_orders['total_average'],
      per_sale: todays_orders['order_products_count']
    }

    day_names = Date::DAYNAMES
    initial_stat_hash = day_names.map { |day| [day, 0] }.to_h # { [Sunday: 0], [Monday: 0], [Tuesday: 0], ....}

    orders_by_day = Order
                    .select('EXTRACT(DOW FROM created_at) AS day_of_week, SUM(total) AS total_sum')
                    .where('created_at > ?', Time.now.midnight - 7.days)
                    .group('day_of_week')
                    .order('day_of_week')

    orders_by_day = orders_by_day.map { |order| [day_names[order.day_of_week.to_i], order.total_sum.to_f] }.to_h

    @revenue_by_day = initial_stat_hash.merge!(orders_by_day).to_a

    @unfulfilled_orders = Order.where(fulfilled: false).order(created_at: :desc).limit(10)
  end
end

app/controllers/assets_controller.rb
# frozen_string_literal: true

class AssetsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: %i[serve_js]

  def serve_js
    file_name = params[:filename]

    file_path = Rails.root.join("vendor", "_", file_name)

    if File.exist? file_path
      send_file(file_path, type: "application/javascript", disposition: "inline")
    else
      render plain: "File not found", status: :not_found
    end
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def show
  end
end

app/controllers/checkouts_controller.rb
# frozen_string_literal: true

class CheckoutsController < ApplicationController
  def create
    result = Stripe::CheckoutService.new(params[:cart]).call

    render json: result, status: 200
  end

  def success
    render :success
  end

  def cancel
    render :cancel
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @main_categories = Category.take(4)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.limit(10)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/webhooks_controller.rb
# frozen_string_literal: true

# controller to process all webhooks
class WebhooksController < ApplicationController
  skip_forgery_protection

  def stripe
    Stripe.api_key = Rails.application.credentials.stripe.secret_key
    payload = request.body.read
    sig_header = request.env['HTTP_STRIPE_SIGNATURE']
    endpoint_secret = Rails.application.credentials.stripe.webhook_secret_key

    begin
      event = Stripe::Webhook.construct_event(payload, sig_header, endpoint_secret)
    rescue JSON::ParserError => e
      # send to system monitor(rollbar, honeybadger etc.)
      render json: { message: e.message }, status: 500 and return
    rescue Stripe::SignatureVerificationError => e
      # send to system monitor(rollbar, honeybadger etc.)
      render json: { message: e.message }, status: 500 and return
    end

    case event.type
    when 'checkout.session.completed'
      session = event.data.object
      shipping_details = session['shipping_details']
      address = if shipping_details
                  "#{shipping_details['address']['line1']} #{singleton_details['address']['city']},
                  #{shipping_details['address']['state']} #{shipping_details['address']['postal_code']}"
                else
                  ''
                end
      # TODO: create order serivce to create orders
      order = Order.create!(customer_email: session['customer_details']['email'],
                            total: session['amount_total'],
                            address:,
                            fulfilled: false)
      full_session = Stripe::Checkout::Session.retrieve({
                                                          id: session.id,
                                                          expand: ['line_items']
                                                        })
      line_items = full_session.line_items
      line_items['data'].each do |item|
        product = Stripe::Product.retrieve(item['price']['product'])
        product_id = product['metadata']['product_id'].to_i
        stock_id = product['metadata']['product_stock_id'].to_i

        OrderProduct.create!(order:,
                             product_id:,
                             quantity: item['quantity'],
                             size: product['metadata']['size'])
        Stock.find(stock_id).decrement!(:amount, item['quantity'])
      end
    else
      # send to system monitor(rollbar, honeybadger etc.)
      p "Unhandled event type: #{event.type}"
    end

    render json: { message: 'success' }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stocks_helper.rb
# frozen_string_literal: true

module StocksHelper
end

app/views/admin/index.html.erb
<h1 class="text-4xl text-gray-800 font-medium mb-4">Admin Dashboard</h1>

<div class="flex justify-between flex-wrap mt-8 w-full intes-center max-w-4xl">
  <h2 class="text-2xl text-orange-800 font-medium mb-4">
    Daily Stats
  </h2>
  <div class="flex gap-10 flex-col md:flex-row justify-between w-full">
    <div class="max-w-sm rounded overflow-hidden shadow-xl bg-gradient-to-r from-green-500 to-green-400">
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2 text-white">
          Revenue
        </div>
        <p class="text-white text-base">
          $<%= @dashboard_data[:revenue] ? (@dashboard_data[:revenue]/100.0).to_s : "0" %>
        </p>
      </div>
    </div>
    <div class="max-w-sm rounded overflow-hidden shadow-xl bg-gradient-to-r from-green-500 to-green-400">
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2 text-white">
          Total Sales
        </div>
        <p class="text-white text-base">
          <%= @dashboard_data[:orders_count] ? @dashboard_data[:orders_count].to_s : "0" %>
        </p>
      </div>
    </div>
    <div class="max-w-sm rounded overflow-hidden shadow-xl bg-gradient-to-r from-green-500 to-green-400">
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2 text-white">
          Items/Sale
        </div>
        <p class="text-white text-base">
          $<%= @dashboard_data[:per_sale].to_i %>
        </p>
      </div>
    </div>
    <div class="max-w-sm rounded overflow-hidden shadow-xl bg-gradient-to-r from-green-500 to-green-400">
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2 text-white">
          Avg. Sales
        </div>
        <p class="text-white text-base">
          $<%= @dashboard_data[:avg_sale] ? @dashboard_data[:avg_sale].to_s : "0" %>
        </p>
      </div>
    </div>    
  </div>

  <div class="my-8 w-full">
    <h2 class="text-2xl text-gray-800 font-medium mb-4">Revenue</h2>
    <div class="w-full" data-controller="dashboard" data-dashboard-revenue-value="<%= @revenue_by_day.to_json %>">
      <canvas id="revenueChart"></canvas>
    </div>
  </div>

  <%= render "admin/partials/recent_unfulfilled_orders", orders: @unfulfilled_orders %>
</div>

app/views/admin/partials/_recent_unfulfilled_orders.html.erb
<div class="flex flex-col w-full">
  <h2 class="text-2xl text-gray-800 mb-4 font-medium">
    Recent Unfulfilled Orders
  </h2>
  <div class="overflow-x-auto">
    <table class="min-w-full bg-gray-100" style="border-collapse: separate; border-spacing: 0;">
      <thead>
        <tr class="text-gray-800">
          <th class="px-6 py-3 border-b-2 border-gray-200 bg-gray-100">
            Order ID
          </th>
          <th class="px-6 py-3 border-b-2 border-gray-200 bg-gray-100">
            Customer
          </th>
          <th class="px-6 py-3 border-b-2 border-gray-200 bg-gray-100">
            Date
          </th>
          <th class="px-6 py-3 border-b-2 border-gray-200 bg-gray-100">
            Amount
          </th>
        </tr>
      </thead>
      <tbody class="text-gray-700">
        <% orders.each do |order| %>
          <tr>
            <td class="px-6 py-4 border-b border-gray-200">
              <%= link_to order.id, admin_order_path(order), class: "underline" %>
            </td>
            <td class="px-6 py-4 border-b border-gray-200">
              <%= order.customer_email %>
            </td>
            <td class="px-6 py-4 border-b border-gray-200">
              <%= order.created_at.strftime("%B %d, %Y %H:%M") %>
            </td>
            <td class="px-6 py-4 border-b border-gray-200">
              <%= (order.total/100).to_s %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-gray-800 text-white">
  <div class="max-2-6xl max-auto px-4 py-10 md:py-20">
    <div class="xl:grid xl:grid-col-3 xl:gap-8">
      <div class="space-y-8 xl:col-span-1">
        <h3 class="text-sm font-semibold text-gray-200 tracking wider uppercase">
          About Ecommerce
        </h3>
        <p class="text-white leading-6">
          Our application is a leader in trading. Offer wide range of products. Great and best shopping experience
        </p>
      </div>

      <div class="mt-12 grid grid-cols-2 gap-8 xl:mt-0 xl:col-span-2">
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div>
            <h3 class="text-sm font-semibold text-gray-200 traching wider uppercase">Quick Links</h3>
            <ul class="mt-4 space-y-4">
              <li>
                <%= link_to "Home", root_path, class: "text-base leading-6 text-white hover:text-gray-100" %>
              </li>
            </ul>
          </div>
        </div>        
      </div>

      <div class="mt-8 mb-8 grid grid-cols-2 gap-8">
        <div>
          <h3 class="text-sm font-semibold text-gray-200 traching wider uppercase">Contact</h3>
          <ul class="mt-4 space-y-4">
            <li>
              <p class="text-base leading-6 text-white"> Ecommerce Avenue 12 <br>Great Town, GT 123</p>
            </li>
            <li>
              <p class="text-base leading-6 text-white">Email: admin@exmaple.com</p>
            </li>
          </ul>
        </div>
      </div>
      <div></div>
      <div class="border-t border-gray-700">
        <div class="max-w-6xl mx-auto px-4 py-6 md:flex md:items-center md:justify-between">
          <p class="mt-6 text-base leading-6 text-gray-400 md:mt-0 md:order-1">
            &copy; <%= Time.now.year %> Admin, Inc. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="fixed w-full top-0 bg-gray-100 z-10 py-4">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex item-center justify-between h-16">
      <div class="flex-1 flex items-center justif-center sm:items-stretch sm:justify-between">
        <div class="hidden sm:flex items-center justify-center">
          <div class="flex space-x-10">
            <%= link_to "Shop", root_path, class: "text-gray-500 hover:underline py-2 rounded-md text-md font-medium" %>
          </div>
        </div>
        <div class="flex-shrink-0 flex items-center">
          <%= link_to root_path do %>
            <%= image_tag 'logo.png', class: "block lg:hidden h-20 w-auto" %>
          <% end %>
          <%= link_to root_path do %>
            <%= image_tag 'logo.png', class: "hidden lg:block h-20 w-auto" %>
          <% end %>
        </div>
        <div class="hidden sm:flex sm:ml-6 items-center justify-center">
          <div class="flex space-x-10">
            <%= link_to cart_path, class: "text-gray-500 hover:underline py-2 rounded-md text-md font-medium" do %>
              <%= icon 'fa-solid', 'shopping-cart' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>