config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins

  resources :admin, only: %i[index]

  namespace :admin do
    resources :products do
      resources :stocks
    end
    resources :categories
    resources :orders
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ('/')
  root to: 'home#index'

  authenticated :admin_user do
    root to: 'admin#index', as: :admin_root
  end

  resources :categories, only: %i[index show]
  resources :products, only: %i[index show]

  post 'checkout' => 'checkouts#create'
  get 'cart' => 'carts#show'

  # Route to handle external reference in chart.js
  get '/_/:filename', to: 'assets#serve_js', constraints: { filename: /.*\.js/ }

  # Stripe routes
  get 'stripe_payment_success' => 'checkouts#success'
  get 'stripe_payment_cancel' => 'checkouts#cancel'
  post 'stripe_webhooks' => 'webhooks#stripe'
end

app/models/category.rb
# frozen_string_literal: true

# a class to create categories
class Category < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
    attachable.variant :medium, resize_to_limit: [250, 250]
  end

  has_many :products
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

# class to set CRUD methods for Categories in admin dashboard
class Admin::CategoriesController < AdminController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /admin/categories or /admin/categories.json
  def index
    @admin_categories = Category.all
  end

  # GET /admin/categories/1 or /admin/categories/1.json
  def show; end

  # GET /admin/categories/new
  def new
    @admin_category = Category.new
  end

  # GET /admin/categories/1/edit
  def edit; end

  # POST /admin/categories or /admin/categories.json
  def create
    @admin_category = Category.new(admin_category_params)

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to admin_category_url(@admin_category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @admin_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/categories/1 or /admin/categories/1.json
  def update
    respond_to do |format|
      if @admin_category.update(admin_category_params)
        format.html { redirect_to admin_category_url(@admin_category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1 or /admin/categories/1.json
  def destroy
    @admin_category.destroy!

    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @admin_category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_category_params
      params.require(:category).permit(:name, :description, :image)
    end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products.includes(images_attachments: :blob)

    @products = @products.where('price >= ?', params[:min]) if params[:min].presence
    @products = @products.where('price <= ?', params[:max]) if params[:max].presence
  end
end

app/helpers/admin/categories_helper.rb
# frozen_string_literal: true

module Admin::CategoriesHelper
end

app/views/categories/index.html.erb
Hello that is category index page

app/views/categories/show.html.erb
<h1>Category Show Page</h1>
<div class="min-h-screen flex justify-center">
  <div class="flex flex-wrap flex-col mt-6">
    <h2 class="text-lg text-gray-800 mb-2">
      <%= @category.name %>
    </h2>
    <%= form_with url: category_path(@category), method: :get, class: "flex flex-col" do |form| %>
      <%= form.number_field :min, value: params[:min], placeholder: "Min Price", class: "border border-gray-800 rounded-md p-2 w-32" %>
      <%= form.number_field :max, value: params[:max], placeholder: "Max Price", class: "border border-gray-800 rounded-md p-2 mt-2 w-32" %>
      <%= form.submit "Filter", class: "bg-gray-800 text-white rounded-md p-2 mt-2 cursor-pointer" %>
    <% end %>
    <%= form_with url: category_path(@category), method: :get, class: "flex flex-col" do |form| %>
      <%= form.submit 'Clear', class: "bg-gray-800 text-white rounded-md p-2 mt-2 cursor-pointer" %>
    <% end %>
  </div>
  <div class="flex flex-wrap mt-6 gap-10 flex-row justify-center items-start">
    <% if @products.empty? %>
      <p class="text-2xl text-left text-gray-800">
        No products found...
      </p>
    <% else %>
      <% @products.each do |p| %>
        <%= link_to product_path(p) do %>
          <div class="max-w-xs flex flex-col p-4 justify-center items-center">
            <%= p.images.first ? 
                image_tag(p.images.first.variant(:medium), class: "rounded") : 
                image_tag("http://via.placeholder.com/250", class: "rounded") %>
            <p class="mt-6 font-medium text-gray-800">
              <%= p.name %>
            </p>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>